export default {
  border: {
    radius: '0.4rem',
  },
  font: {
    primary:
      "Montserrat, -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Oxygen, Ubuntu, Cantarell, 'Open Sans', 'Helvetica Neue', sans-serif",
    secondary:
      "Bitter, -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Oxygen, Ubuntu, Cantarell, 'Open Sans', 'Helvetica Neue', sans-serif",
    regular: 400,
    medium: 500,
    semi: 600,
    sizes: {
      xsmall: '1.2rem',
      small: '1.4rem',
      medium: '1.6rem',
      large: '1.8rem',
      xlarge: '2.0rem',
      xxlarge: '2.8rem',
    },
  },
  colors: {
    primary: '#fdb755',
    secondary: '#1e2537',
    mainBg: '#ffffff',
    black: '#000000',
    lightGray: '#93918f',
    gray: '#787878',
    darkGray: '#636363',
    gradientFrom: '#fefefe',
    gradientTo: '#e9e9e9',
    heatmap0: '#e0e592',
    heatmap1: '#aed396',
    heatmap2: '#a9d194',
    heatmap3: '#a0ce93',
    heatmap4: '#99cd94',
    heatmap5: '#8cc894',
    heatmap6: '#5eb391',
    heatmap7: '#5db492',
    heatmap8: '#5cb391',
    heatmap9: '#5aad8c',
    heatmap10: '#3984a3',
  },
  spacings: {
    xxsmall: '0.8rem',
    xsmall: '1.6rem',
    small: '2.4rem',
    medium: '3.2rem',
    large: '4.0rem',
    xlarge: '4.8rem',
    xxlarge: '5.6rem',
  },
}
